### ISSUE TITLE
Different mods, their status

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#5]
> **tjayharvey** said in the Obsidian thread
> It turned out I was mostly confused. I was excluding UICustomization and trying to resolve the resulting compile errors, and ended up commenting out/excluding more than I needed to. However, there are at least two mods that depend on UICustomization - the DropButtonMod and the Console. The former looks like a stray using (commenting it out lets it compile, and there are no problems when patching, but I haven't attempted to test it yet). The latter is only two commands.
> 
> However, saving the preferences in Options is definitely malfunctioning. It prompts me to save options and won't respond to either choice, and appears in lots of situations that don't appear correct - it will block you from saving your game, for instance. It somehow seems to work fine if you select the "Autosave on changes" checkbox.  Since this is used to save changes to the settings the other mods used, it also looks like a good early fix candidate.
> 
> I've sent the pull request for the initial fix to Program. I had to restart from scratch (because of how I created the initial repo), and when I copied the changes back in it somehow decided I changed the entire file, so it looks a little weird. Hopefully the changes to the Console mod won't look so ugly and will be easier for you to parse.
> 
> Here's a list of definitely broken mods:
> CombatLooting (signature change in source, compiles fine but fails patching)
> FastSneak (sneaking-related)
> NoEngagement (sneaking-related)
> OnLevelLoad (looks like AI change, also depends on UICustomization)
> SaveXML (change in PersistanceManager source)
> SelectionCircles (source object was generally refactored)
> Targeting (same)
> UICustomization (party bar stuff, looks like the source UIPartyPortrait and UIMapTooltip were changed)
> 
> Of course, that doesn't mean everything else is working right, just that it doesn't immediately break. Will require some testing.
## Scrap
- [x] **AI:** Best to remove it for now. Like I said, since they changed the AI, it might not be necessary, and may actually make things worse. 
- [x] **SaveXML:** Was never finished.  
## Probably Works
- [x] **Per Encounter Spells:** Works and tested thoroughly. 
- [x] **Cipher Focus:** :) Related: #7
- [x] **Bonus Spells in Grimoire:** Seems to work. Related: #13, #12  
- [x] **GameSpeed:** Seems to work as far as I can see.
- [x] **FastSneak:** Seems to be working. Related: #15 
- [x] **Always ShowCircles:** Seems to work.
- [x] **Targeting:** It does probably work.
- [x] **OneTooltip**: Seems to work. Related: #19 
- [x] **Bonus Spells per Day:** Probably works.
- [x] **Toggle Walking Mode:** Rewritten and works. See #17.
- [x] **Console:** Works. Related: #24
- [x] **Options:** Works. Related: #24
## Seems to Work
- [x] **Camera:** This just changes the default zoom. This had to be merged with changes from 2.0, and it works. However, we should be on the lookout for any bugs.
- [x] **Experience:** Seems to work.
- [x] **Backer Names**: Seems to work.
- [x] **Blue Circles (±IE Blue):** Seems to work. The fix is so simple I doubt it will cause any trouble at all.
- [x] **CombatOnly (spells):** Seems to work.
- [x] **CombatLooting:** Seems to work.
- [x] **Game Object Browser:** I don't know its status, actually. This is a pretty important tool for debugging.
- [x] **NoEngagement:** Has been merged, needs testing.
- [x] **UI Customization:** Seems to work.
## Needs Testing
- [ ] **Disposition fix:** Will require testing.

**Comment by tjayharvey** [comment]
From a functional perspective sneaking shouldn't be that hard. I found the appropriate functions to use for it now. I THOUGHT I had Fast Sneak fixed but wasn't able to get any version to perform reasonably (even when I copied the verbatim code from JustDecompile and didn't introduce any changes). I'll do some further testing tonight or tomorrow. I didn't know about the exceptions, so I'll check those.

I have tested:
Console (not every command, I don't even completely understand what some of the more cryptic ones are for).
Spells Per Encounter (for the spell levels that it covers, just a smoke test. I'll try to exhaustively test it soon).

**Comment by GregRos** [comment]
From a functional perspective yeah, but... from my experience, it can get very messy. Obsidian's code can easily throw `NullReferenceException`s if you do something slightly out of line, for example.  And you don't have a debugger or anything to see where the error is, just some vague log entries.

I have no idea why the issue with Fast Sneak would arise. Bear in mind that it _could_ be a problem with Patchwork, though it's unlikely due to the amount of testing it has undergone. Also, are you keeping an eye on the ILVerify output at the end of the patching log? You should take note of any errors.

Also, read the bit about debugging in the readme. It talks about exceptions, and has a few tips.

**Comment by tjayharvey** [comment]
I have PEVerify running, and it checks out without any errors on each pass. ILSpy isn't currently set to run as far as I can see.

I was really just messing with Sneak far after I should have gone to bed, and only tried a few basic tests. Should know more after I take another crack at it.

**Comment by GregRos** [comment]
Yeah, I only run it if PEVerify shows any errors. There haven't been errors in a while though.

**Comment by tjayharvey** [comment]
I figured out what was wrong with my FastSneak trial. I didn't replace base.Update() with BaseUpdate(), so it was causing an infinite loop. Fun. It now works.

So, FastSneak currently allows you to move fast as long as nobody in your party can see enemies. Given that stealth is individual now, should we allow a given party member to move fast as long as that person can't see an enemy, or does my rogue scouting ahead and spotting the first monster now slow down stealth for anyone that chooses to go into stealth and come up to him? Also, the detection of "Can I see a monster?" appears active only if you have the Auto-Pause setting on for that - this seems like it needs to be on if FastSneak is on as well, so that we can slow down the moving player appropriately.

Thoughts?

**Comment by GregRos** [comment]
I really think we shouldn't increase the speed of stealth if enemies are involves in any way. Otherwise it becomes more than a convenience feature; it actually gives you some kind of tactical advantage.

As for the auto-pause thing, have you tested it?

**Comment by tjayharvey** [comment]
That's the only reason I found it. It wasn't shutting off fast sneak when I went into sight range, but when I ticked the Auto-Pause box it started doing so. I've also applied a fix to make it start working and tested that too.

I can see your point. I'll check it in that way when it's ready. 

Personally, I will probably leave it on in my own version. The "can see enemies" range is actually fairly long if the enemy isn't under Fog of War, so the only realistic tactical use of it would be if you had a back hallway/path or some other form of blocking cover you could use to flank the enemy while remaining with a blocked line of sight. When I was testing this version, I snuck one person up just close enough to see an enemy without any detection chance, and then snuck a second person up. The second one slowed down significantly before the first.

**Comment by GregRos** [comment]
We could put a dropdown so people can choose. I'd imagine many people think that way.

**Comment by tjayharvey** [comment]
Tested Bonus Spells Per Day up to Intellect values of 30. Appears to match formula. I think it's safe to mark that one off.

The Combat Only mod (which actually removes Combat Only from spells) also looks good.

**Comment by GregRos** [comment]
@tjayharvey Can you check the boxes yourself?

**Comment by tjayharvey** [comment]
Yes, I can check them. But can't move them from category to category.

**Comment by tjayharvey** [comment]
What are the next steps? I'm not 100% Sure how to test the NoDisengagement mod, and I don't have a save with the npc paladin atm. Do we want to go ahead and release a beta version and take bug reports? Or spend some more time testing internally?

**Comment by GregRos** [comment]
The no engagement mod was supposed to remove disengagement attacks. I tested and it and it does do that, but it may have also been supposed to remove the special engagement indicator/selection circle. It does seem to attempt to do this, but that part doesn't work. The problem is I don't know if it did work before, so I don't know if it's something that should be fixed, or something that never worked (there have been bits like that in the code) and so has to be done in another way. A lot of people do use it for reasons I don't understand, so once we release it I guess we'll find out.

I'll move it to the seems to work part.

I have no idea at all how to test the disposition fix. I'm not even sure what it does, to be honest.

I vote that we test it internally for a bit more. 

There is also that portrait glow thing in the ui customization part. I'll take care of it.

**Comment by GregRos** [comment]
We don't need this anymore.
